#!/usr/bin/env bash
# Convert raw packs in audio-wip/ into the MP3s the game ships.
#
# By default only the files named in lib/sound/config.json are built — the
# picked cue per sound — so the deployed set stays small. `--all` builds the
# whole library for a /sound lab session, where every candidate is needed.
#
# Output: public/audio/<pack>/<name>.mp3, loudness-normalised, mono, 44.1 kHz.
# Safari has no Ogg support and MP3 decodes everywhere the game runs.
set -euo pipefail
cd "$(dirname "$0")/.."

SRC=audio-wip
OUT=public/audio
MODE=${1:-picked}

convert() {
  local in="$1" out="$2"
  mkdir -p "$(dirname "$out")"
  ffmpeg -loglevel error -y -i "$in" \
    -af "loudnorm=I=-16:TP=-1.5:LRA=11" \
    -ac 1 -ar 44100 -codec:a libmp3lame -q:a 4 "$out"
}

# Map a shipped path back to its raw source (Freesound files carry an id and
# author prefix that the shipped name drops).
source_for() {
  local rel="$1" pack name
  pack=${rel%%/*}
  name=${rel#*/}; name=${name%.mp3}
  find "$SRC/$pack" -type f \( -name "$name.ogg" -o -name "$name.wav" -o -name "*__$name.wav" -o -name "*__$name.ogg" \) | head -1
}

rm -rf "$OUT"
if [ "$MODE" = "--all" ]; then
  for pack in electro-sounds interface-sounds sc-fi-sounds; do
    find "$SRC/$pack" -type f \( -name '*.ogg' -o -name '*.wav' \) | while read -r f; do
      name=$(basename "$f"); name=${name%.*}; name=${name##*__}
      convert "$f" "$OUT/$pack/$name.mp3"
    done
  done
else
  node -e 'for (const f of new Set(Object.values(require("./lib/sound/config.json")))) console.log(f)' \
  | while read -r rel; do
    src=$(source_for "$rel")
    if [ -z "$src" ]; then echo "missing source for $rel" >&2; exit 1; fi
    convert "$src" "$OUT/$rel"
  done
fi

# Regenerate the library listing the lab browses.
node -e '
const fs=require("fs"),p=require("path");
const root="public/audio"; const out=[];
for (const pack of fs.readdirSync(root).sort()) { const d=p.join(root,pack); if(!fs.statSync(d).isDirectory()) continue;
  for (const f of fs.readdirSync(d).sort()) if (f.endsWith(".mp3")) out.push(`${pack}/${f}`); }
fs.writeFileSync("lib/sound/library.ts", `/**\n * Every shipped sound file, for the /sound lab\x27s browse-all pickers.\n * Generated by scripts/build-audio.sh; do not edit by hand.\n */\nexport const SOUND_LIBRARY: readonly string[] = ${JSON.stringify(out,null,2)};\n`);
'
echo "done ($MODE): $(find "$OUT" -name '*.mp3' | wc -l | tr -d ' ') files, $(du -sh "$OUT" | cut -f1)"
