/**
 * Every shipped sound file, for the /sound lab's browse-all pickers.
 * Generated by scripts/build-audio.sh; do not edit by hand.
 */
export const SOUND_LIBRARY: readonly string[] = [
  "electro-sounds/electro-close-sound.mp3",
  "electro-sounds/electro-loose-sound.mp3",
  "electro-sounds/electro-open-sound.mp3",
  "electro-sounds/electro-success-sound.mp3",
  "electro-sounds/electro-win-sound.mp3",
  "interface-sounds/bong_001.mp3",
  "interface-sounds/click_001.mp3",
  "interface-sounds/click_003.mp3",
  "interface-sounds/confirmation_001.mp3",
  "interface-sounds/confirmation_002.mp3",
  "interface-sounds/confirmation_003.mp3",
  "interface-sounds/drop_002.mp3",
  "interface-sounds/error_003.mp3",
  "interface-sounds/error_005.mp3",
  "interface-sounds/error_008.mp3",
  "interface-sounds/glass_001.mp3",
  "interface-sounds/maximize_006.mp3",
  "interface-sounds/maximize_008.mp3",
  "interface-sounds/tick_001.mp3",
  "interface-sounds/tick_002.mp3",
  "interface-sounds/toggle_001.mp3",
  "interface-sounds/toggle_002.mp3",
  "interface-sounds/toggle_003.mp3",
  "sc-fi-sounds/forceField_004.mp3",
  "sc-fi-sounds/impactMetal_000.mp3"
];
